### PR TITLE
2.2.0

### PR DESCRIPTION
**Pull request by DanielSchaffer**
Release for the following issue fixes and PRs:
- PR #24 - fix not transpiling commonjs dependencies
- PR #25 - add dynamic import with expression to `es6-dynamic-import` example
- #23 - correctly handle and name dynamic imports with expressions

The above changes are available as a prerelease in [webpack-babel-multi-target-plugin@2.2.0-alpha.3](https://www.npmjs.com/package/webpack-babel-multi-target-plugin/v/2.2.0-alpha.3)

@saumitrab @Georgegriff @ggriffithsIDBS - please let me know if this version solves your problems and I'll promote this to a regular release.

### CODE REVIEW

**Comment by Georgegriff** [comment]
I downloaded the provided version and my build no longer showed the error :) thanks 😊

**Comment by DanielSchaffer** [comment]
@Georgegriff @ggriffithsIDBS I also added more documentation around naming dynamic/lazy chunks:  https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/tree/release/2.2.0#usage-with-es6-dynamic-imports-including-angular-lazy-routes

**Comment by DanielSchaffer** [comment]
Sorry folks, this is going to take a little longer ... something is up with the transpiling and both bundles are broken now :\

**Comment by Georgegriff** [comment]
No worries, I really appreciate all your efforts 😊

**Comment by DanielSchaffer** [comment]
@Georgegriff @ggriffithsIDBS @saumitrab 

New prerelease: [webpack-babel-multi-target-plugin@2.2.0-alpha.3](https://www.npmjs.com/package/webpack-babel-multi-target-plugin/v/2.2.0-alpha.3)

**Comment by DanielSchaffer** [comment]
If nobody has any objections, I'll release `2.2.0` tomorrow around noon US Pacific time.

**Pull request merged**
