### PR TITLE
add additionalModules option

### PR DESCRIPTION
**Pull request by DanielSchaffer**
`additionalModules` is implemented by prepending any defined modules to the entry module. For example:

```
{
  entry: {
    main: './src/main.js',
  },
  plugins: [
    new BabelMultiTargetPlugin({
      targets: {
        modern: true,
        legacy: {
         additionalModules: ['some-module'],
        },
      },
    })
  ],
}
```
The above effectively does this, but only for the "legacy" bundle:
```
{
  entry: {
    main: ['some-module', './src/main.js'],
  },
}
```

Note that including modules in this way means that they'll be processed the same way any other JS module would, to include being run through Babel and any other matching loaders.

### CODE REVIEW

**Comment by platosha** [comment]
I have one small catch about this approach. Because there is no explicit require for `'some-module'` in `'main.js'`, it seems that their order of execution is determined alphabetically. Therefore, since I want my polyfills to be executed before any other code, I had to use an underscore prefix in the filename, e.g., `_polyfills.js`.

Using array as an entry point ends up with the same catch, so I think, it is not something about the plugin, but rather a regular webpack behaviour.

This is not a big issue, though, but maybe worth documenting.

Otherwise, works as expected! Thank you.  🙇

**Comment by DanielSchaffer** [comment]
@platosha actually, it looks like the alphabetization is a bug somewhere in the plugin. When I omit the plugin, entry modules are loaded in the order they're defined. This behavior is present in the current stable release as well (v2.0.1), so I'm guessing it's something to do with how I handle array entries. I've opened a separate issue to fix it (#19)

**Comment by DanielSchaffer** [comment]
@platosha try [v2.1.0-alpha.9](https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/releases/tag/v2.1.0-alpha.9) - should fix your ordering issue

**Comment by LarsDenBakker** [comment]
This is great, I'm glad to see this :)

**Comment by LarsDenBakker** [comment]
for what it's worth this works as expected for me. I'm using it to inject only es2015 polyfills to the legacy build, and turned off any polyfilling in babel to keep the modern bundle small (don't want to polyfill iterables dom nodes etc. at the cost of 40kb)

**Comment by DanielSchaffer** [comment]
@LarsDenBakker polyfills would be based on usage and the browser targets - you can customize the `browserslist` to your liking, which might be a better practice than turning it them entirely.

**Comment by LarsDenBakker** [comment]
You're right that would be a nice setup, but in my opinion it's not good for production apps. The web is bloated with javascript. A good recommended budget is 100-150kb for the initial render. If 50kb of that is spent polyfilling iterable dom nodes and `String.prototype.padStart` I'd rather opt out of that.

The es2015 polyfills are important for writing good code, and thanks to this plugin we can load it only on IE11. All other browsers support this natively.

Syntax is usually cheap to transform, so I'd like to use the browserslist for that.

**Comment by DanielSchaffer** [comment]
@LarsDenBakker I'm not suggesting adding polyfills you don't think you need - I'm just suggesting that if you want to avoid polyfills in your "modern" bundle, then adjust your browserslist accordingly rather than disabling it entirely. I know _I_ can't keep track (nor do I want to have to) of what features I'm using and which browsers they're available in. The risk you run by turning them off entirely is that you end up using something you don't realize isn't supported as broadly as you believed - particularly as new features are added to the language and browser APIs.

**Pull request merged**
