### PR TITLE
Add nomodule fix for Safari 10.1

### PR DESCRIPTION
**Pull request by DanielSchaffer**
Adds a `safari10NoModuleFix` option which embeds a polyfill to work around Safari 10.1's missing support for `<script nomodule>`. Must be used with `HtmlWebpackPlugin` to work, otherwise the script must be manually included in your HTML template.

Also provides a basis for testing the example projects against BrowserStack to ensure functionality across multiple browsers.

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
@DanielSchaffer One issue with using `'external'`:
```
ERROR in   Error: ENOENT: no such file or directory, open '/Users/XXXXXX/Sites/poly3webpack/node_modules/webpack-babel-multi-target-plugin/src/safari-nomodule-fix/safari.nomodule.fix.js'
  
  - safari.nomodule.fix.plugin.js:65 SafariNoModuleFixPlugin.<anonymous>
    [poly3webpack]/[webpack-babel-multi-target-plugin]/src/safari-nomodule-fix/safari.nomodule.fix.plugin.js:65:146
  
  - Generator.next
  
  - safari.nomodule.fix.plugin.js:7 
    [poly3webpack]/[webpack-babel-multi-target-plugin]/src/safari-nomodule-fix/safari.nomodule.fix.plugin.js:7:71

```

**Comment by DanielSchaffer** [comment]
Whups, looks like some files got missed from the publishing directory. `v2.1.0-alpha.4` should fix it.

**Comment by moderndeveloperllc** [comment]
@DanielSchaffer It looks like the file is there, but one directory down from where it's expected: 

Looking for `node_modules/webpack-babel-multi-target-plugin/src/safari-nomodule-fix/safari.nomodule.fix.js`

Located: `node_modules/webpack-babel-multi-target-plugin/src/safari.nomodule.fix.js`

**Comment by DanielSchaffer** [comment]
Oh whups, so it is ... gotta fix the copy command to preserve the path

**Comment by DanielSchaffer** [comment]
@moderndeveloperllc try `2.1.0-alpha.5`

**Comment by moderndeveloperllc** [comment]
@DanielSchaffer Looks good to go! Thanks.

**Review by DanielSchaffer — COMMENTED** [review]
TODO - need to figure out if adding `@babel/plugin-transform-runtime` as a default is the right thing to do. I know some folks prefer using `fast-async` instead so I just need to make sure this doesn't shut them out of doing that. Also, sorry for the scope creep on this PR/branch ... oops.

**Pull request merged**
